import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import "./home.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="main">
        <nav>
          <ul className="nav">
             <li className="logo">Pokemon</li>
             <Link href={"/"}>
                <li>Home</li>
             </Link>
             <Link href={"/client"}>
                <li>Client</li>
             </Link>
             <Link href={"/server"}>
                <li>Server</li>
             </Link>
          </ul>
        </nav>
      </div>
        {children}
      </body>
    </html>
  );
}
